// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bottomnav/StateCart.tsx": () => import("../components/mockups/bottomnav/StateCart.tsx"),
  "./components/mockups/bottomnav/StateHome.tsx": () => import("../components/mockups/bottomnav/StateHome.tsx"),
  "./components/mockups/bottomnav/UXReview.tsx": () => import("../components/mockups/bottomnav/UXReview.tsx"),
  "./components/mockups/brands-bar/V1DarkCinematic.tsx": () => import("../components/mockups/brands-bar/V1DarkCinematic.tsx"),
  "./components/mockups/brands-bar/V2FrostedGlass.tsx": () => import("../components/mockups/brands-bar/V2FrostedGlass.tsx"),
  "./components/mockups/brands-bar/V3EditorialWarm.tsx": () => import("../components/mockups/brands-bar/V3EditorialWarm.tsx"),
  "./components/mockups/brands-bar/V4NoirMarquee.tsx": () => import("../components/mockups/brands-bar/V4NoirMarquee.tsx"),
  "./components/mockups/brands-bar/V5GoldGradient.tsx": () => import("../components/mockups/brands-bar/V5GoldGradient.tsx"),
  "./components/mockups/brands-strip/DarkCinematic.tsx": () => import("../components/mockups/brands-strip/DarkCinematic.tsx"),
  "./components/mockups/brands-strip/EditorialMinimal.tsx": () => import("../components/mockups/brands-strip/EditorialMinimal.tsx"),
  "./components/mockups/brands-strip/FloatingPills.tsx": () => import("../components/mockups/brands-strip/FloatingPills.tsx"),
  "./components/mockups/brands-strip/LuxuryMarquee.tsx": () => import("../components/mockups/brands-strip/LuxuryMarquee.tsx"),
  "./components/mockups/brands-strip/NeonGlow.tsx": () => import("../components/mockups/brands-strip/NeonGlow.tsx"),
  "./components/mockups/brands-v2/BronzeRibbon.tsx": () => import("../components/mockups/brands-v2/BronzeRibbon.tsx"),
  "./components/mockups/brands-v2/CircleInitials.tsx": () => import("../components/mockups/brands-v2/CircleInitials.tsx"),
  "./components/mockups/brands-v2/PrestigeCards.tsx": () => import("../components/mockups/brands-v2/PrestigeCards.tsx"),
  "./components/mockups/brands-v2/SandTerracotta.tsx": () => import("../components/mockups/brands-v2/SandTerracotta.tsx"),
  "./components/mockups/brands-v2/WarmGlass.tsx": () => import("../components/mockups/brands-v2/WarmGlass.tsx"),
  "./components/mockups/flash-strip/DarkVariant.tsx": () => import("../components/mockups/flash-strip/DarkVariant.tsx"),
  "./components/mockups/flash-strip/GlowVariant.tsx": () => import("../components/mockups/flash-strip/GlowVariant.tsx"),
  "./components/mockups/flash-strip/GradientVariant.tsx": () => import("../components/mockups/flash-strip/GradientVariant.tsx"),
  "./components/mockups/identity/IdentityShowcase.tsx": () => import("../components/mockups/identity/IdentityShowcase.tsx"),
  "./components/mockups/product-card/FeaturedCardPreview.tsx": () => import("../components/mockups/product-card/FeaturedCardPreview.tsx")
};
