// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flash-strip/DarkVariant.tsx": () => import("../components/mockups/flash-strip/DarkVariant.tsx"),
  "./components/mockups/flash-strip/GlowVariant.tsx": () => import("../components/mockups/flash-strip/GlowVariant.tsx"),
  "./components/mockups/flash-strip/GradientVariant.tsx": () => import("../components/mockups/flash-strip/GradientVariant.tsx"),
  "./components/mockups/product-card/FeaturedCardPreview.tsx": () => import("../components/mockups/product-card/FeaturedCardPreview.tsx"),
  "./components/mockups/identity/IdentityShowcase.tsx": () => import("../components/mockups/identity/IdentityShowcase.tsx")
};
