// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brands-strip/DarkCinematic.tsx": () => import("../components/mockups/brands-strip/DarkCinematic.tsx"),
  "./components/mockups/brands-strip/EditorialMinimal.tsx": () => import("../components/mockups/brands-strip/EditorialMinimal.tsx"),
  "./components/mockups/brands-strip/FloatingPills.tsx": () => import("../components/mockups/brands-strip/FloatingPills.tsx"),
  "./components/mockups/brands-strip/LuxuryMarquee.tsx": () => import("../components/mockups/brands-strip/LuxuryMarquee.tsx"),
  "./components/mockups/brands-strip/NeonGlow.tsx": () => import("../components/mockups/brands-strip/NeonGlow.tsx"),
  "./components/mockups/flash-strip/DarkVariant.tsx": () => import("../components/mockups/flash-strip/DarkVariant.tsx"),
  "./components/mockups/flash-strip/GlowVariant.tsx": () => import("../components/mockups/flash-strip/GlowVariant.tsx"),
  "./components/mockups/flash-strip/GradientVariant.tsx": () => import("../components/mockups/flash-strip/GradientVariant.tsx"),
  "./components/mockups/identity/IdentityShowcase.tsx": () => import("../components/mockups/identity/IdentityShowcase.tsx"),
  "./components/mockups/product-card/FeaturedCardPreview.tsx": () => import("../components/mockups/product-card/FeaturedCardPreview.tsx")
};
